working_dir: docker-stacks/
force_recreate: true
auto_discover: true
auto_discover_opts:
  depth: 2
external_secrets:
  TRAEFIK_CF_API_EMAIL: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:traefik/CF_API_EMAIL
  TRAEFIK_CF_DNS_API_TOKEN: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:traefik/CF_DNS_API_TOKEN
  TRAEFIK_OIDC_SECRET: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:traefik/OIDC_SECRET
  TRAEFIK_OIDC_CLIENT_ID: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:traefik/OIDC_CLIENT_ID
  TRAEFIK_OIDC_CLIENT_SECRET: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:traefik/OIDC_CLIENT_SECRET
  POCKETID_DB_PASSWORD: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:pocket-id/DB_PASSWORD
  POCKETID_DB_CONNECTION_STRING: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:pocket-id/DB_CONNECTION_STRING
  POCKETID_ENCRYPTION_KEY: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:pocket-id/ENCRYPTION_KEY
  GRAFANA_ADMIN_PASSWORD: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:grafana/ADMIN_PASSWORD
  GRAFANA_OAUTH_CLIENT_ID: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:grafana/OAUTH_CLIENT_ID
  GRAFANA_OAUTH_CLIENT_SECRET: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:grafana/OAUTH_CLIENT_SECRET
  MINIO_ACCESS_KEY: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:minio/ACCESS_KEY
  MINIO_SECRET_KEY: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:minio/SECRET_KEY
  AUTOBRR_DB_PASSWORD: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/AUTOBRR_DB_PASSWORD
  AUTOBRR_DB_CONNECTION_STRING: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/AUTOBRR_DB_CONNECTION_STRING
  AUTOBRR_OIDC_CLIENT_ID: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/AUTOBRR_OIDC_CLIENT_ID
  AUTOBRR_OIDC_CLIENT_SECRET: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/AUTOBRR_OIDC_CLIENT_SECRET
  WIREGUARD_PRIVATE_KEY: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/WIREGUARD_PRIVATE_KEY
  QUI_OIDC_CLIENT_ID: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/QUI_OIDC_CLIENT_ID
  QUI_OIDC_CLIENT_SECRET: 96236947-c7cb-4a6f-9e7d-9c9ecdfd9468:prod:downloads/QUI_OIDC_CLIENT_SECRET