---
collections:
- name: effectivelywild.technitium_dns
  version: "1.1.2"

roles:
- name: geerlingguy.docker
  version: "7.9.0"
- name: geerlingguy.pip
  version: "3.1.2"
- name: artis3n.tailscale
  version: "v5.0.1"